# -*- coding: utf-8 -*-
"""tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dn7G7rt3qbTIqf5o7LGpbvWsSYDGRR6U

# KAN-RFB Tutorial — import, data, visualize, train, test

Demonstrates the full pipeline: loading data, plotting bubble shapes,
training both modes (constant & xi) via `train_multi_bubble_on_dataset`,
and testing in the static-condensation assembly.

Uses the **frame-split** dataset: D' (centered 70% in log-Pe x log-rho)
is train+val, T = D\D' (frame) is test — covering 4 corner regimes
the model has never seen during training.

---
## Colab setup
Run this cell first if using Google Colab (otherwise skip it).
"""

# Commented out IPython magic to ensure Python compatibility.
# ── 0. COLAB SETUP (run first if using Colab) ─────────────────────────────
import os, torch
if not os.path.isdir('/content/ML_Galerkin_proj'):
    !git clone https://github.com/juanpaca/ML_Galerkin_proj.git /content/ML_Galerkin_proj
# %cd /content/ML_Galerkin_proj
!git pull

# Mount Google Drive and symlink datasets (too large for git)
from google.colab import drive
drive.mount('/content/drive')
# Upload your datasets/ folder to Google Drive/ML_Galerkin_proj/datasets/ first
!rm -rf /content/ML_Galerkin_proj/datasets
!ln -s "/content/drive/MyDrive/ML_Galerkin_proj/datasets" /content/ML_Galerkin_proj/datasets
print("Datasets loaded from Google Drive")

# ── 1. IMPORTS ──────────────────────────────────────────────────────────
import sys, os
# In Colab, CWD is /content; in local, it's the project root
if os.path.isdir('/content/ML_Galerkin_proj'):
    sys.path.insert(0, '/content/ML_Galerkin_proj')
else:
    sys.path.insert(0, '.')

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

from src.dataset_generation import load_dataset, dataset_summary, train_multi_bubble_on_dataset
from src.rfb_bubble import KANBubble1D, MultiKANBubble1D
from src.rfb_exact import ExactRFBubbleSet1D
from src.rfb_assembly import (
    assemble_classical_system, assemble_rfb_condensed_system,
    recover_bubble_coefficients, RFBSolution1D,
)
from src.mesh import Mesh1D
from src.quadrature import GaussLegendre
from src.pde import AdvectionDiffusion1D
from src.basis import LagrangeBasis1D
from src.errors import compute_l2_error, relative_error_percentage

# Move training to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ── 2. LOAD DATASET ─────────────────────────────────────────────────────
ds = load_dataset("rfb_5k_frame")
dataset_summary(ds)

# Dataset structure (frame split):
#   ds["train"]["constant"]  →  {pe, rho, xi, b, db}  — inside D' (70% of log-space)
#   ds["val"][...]            →  validation split — also inside D'
#   ds["test"][...]           →  frame T = D\D' — corners with unseen Pe/rho extremes

xi_full = ds["train"]["constant"]["xi"]  # original FD grid
print(f"xi grid: {xi_full.shape[0]} points")

# ── 3. VISUALIZE BUBBLE SHAPES IN THE DATASET ────────────────────────────
mode = "constant"
train_data = ds["train"][mode]
idx = [0, 100, 200, 300]

fig, axes = plt.subplots(2, 2, figsize=(10, 6), sharex=True, sharey=True)
for ax, i in zip(axes.flat, idx):
    ax.plot(xi_full, train_data["b"][i])
    ax.set_title(f"Pe={train_data['pe'][i]:.2e}, ρ={train_data['rho'][i]:.2e}")
    ax.grid(True, alpha=0.3)
fig.supxlabel("ξ")
fig.supylabel("b̂(ξ)")
fig.tight_layout()
plt.show()

print("Left: low Pe (diffusion-dominated)  →  rounded, symmetric")
print("Right: high Pe (advection-dominated) →  sharp boundary layer at ξ=1")

# ── 4. VISUALIZE FRAME SPLIT & CHECK NO LEAKAGE ─────────────────────────
fm = ds["metadata"]["frame_meta"]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
colors = {"train": "#1F4E79", "val": "#F7DC6F", "test": "#E74C3C"}

# Left: log(Pe) vs log(rho) scatter with D' rectangle
for sname in ["train", "val", "test"]:
    pe_s = ds[sname]["constant"]["pe"]
    rho_s = ds[sname]["constant"]["rho"]
    axes[0].scatter(np.log10(pe_s), np.log10(rho_s),
                     c=colors[sname], alpha=0.3, s=8, label=sname, edgecolors='none')

# Draw D' rectangle
dpe_lo, dpe_hi = fm["d_prime_pe_bounds"]
drho_lo, drho_hi = fm["d_prime_rho_bounds"]
from matplotlib.patches import Rectangle
rect = Rectangle((dpe_lo, drho_lo), dpe_hi - dpe_lo, drho_hi - drho_lo,
                  linewidth=2, edgecolor='green', facecolor='none', linestyle='--',
                  label="D' (train+val)")
axes[0].add_patch(rect)

# Label corners
log_pe_min, log_pe_max = fm["log_pe_range"]
log_rho_min, log_rho_max = fm["log_rho_range"]
corner_labels = [
    (log_pe_min + 0.05*(log_pe_max-log_pe_min), log_rho_min + 0.05*(log_rho_max-log_rho_min), "low Pe\nlow ρ"),
    (log_pe_max - 0.15*(log_pe_max-log_pe_min), log_rho_min + 0.05*(log_rho_max-log_rho_min), "high Pe\nlow ρ"),
    (log_pe_min + 0.05*(log_pe_max-log_pe_min), log_rho_max - 0.10*(log_rho_max-log_rho_min), "low Pe\nhigh ρ"),
    (log_pe_max - 0.15*(log_pe_max-log_pe_min), log_rho_max - 0.10*(log_rho_max-log_rho_min), "high Pe\nhigh ρ"),
]
for cx, cy, label in corner_labels:
    axes[0].text(cx, cy, label, fontsize=8, ha='center', va='center',
                 bbox=dict(boxstyle='round,pad=0.2', facecolor='white', alpha=0.7))

axes[0].set_xlabel("log₁₀(Pe)")
axes[0].set_ylabel("log₁₀(ρ)")
axes[0].set_title("Frame split: D\\'D frame (test in corners)")
axes[0].legend(fontsize=9)
axes[0].grid(True, alpha=0.3)

# Right: per-split statistics
for sname, marker in [("train", "o"), ("val", "s"), ("v", "x")]:
    pass  # remove if unused

# Bar chart: sample counts per split
split_names = ["train", "val", "test"]
counts = [len(ds[s]["constant"]["pe"]) for s in split_names]
bar_colors = [colors[s] for s in split_names]
axes[1].bar(split_names, counts, color=bar_colors, alpha=0.8, edgecolor='black')
axes[1].set_ylabel("Number of samples")
axes[1].set_title(f"Frame split: {counts[0]}tr / {counts[1]}va / {counts[2]}te")
for i, c in enumerate(counts):
    axes[1].text(i, c + 20, str(c), ha='center', fontweight='bold')
axes[1].grid(True, alpha=0.3, axis="y")

plt.tight_layout()
plt.show()

# Verify: no sample overlap between splits
train_ids = set(ds["metadata"]["split_indices"]["train"])
val_ids   = set(ds["metadata"]["split_indices"]["val"])
test_ids  = set(ds["metadata"]["split_indices"]["test"])
print(f"Samples: {len(train_ids)} train / {len(val_ids)} val / {len(test_ids)} test")
print(f"Overlap train∩val: {len(train_ids & val_ids)}")
print(f"Overlap train∩test: {len(train_ids & test_ids)}")
print(f"Overlap val∩test: {len(val_ids & test_ids)}")
print("→ No leakage" if not (train_ids & val_ids or train_ids & test_ids or val_ids & test_ids) else "→ LEAKAGE DETECTED!")

# Print frame corner coverage
pe_te = ds["test"]["constant"]["pe"]
rho_te = ds["test"]["constant"]["rho"]
log_pe_te = np.log10(pe_te)
log_rho_te = np.log10(rho_te)
c1 = ((log_pe_te <= dpe_lo) & (log_rho_te <= drho_lo)).sum()
c2 = ((log_pe_te >= dpe_hi) & (log_rho_te <= drho_lo)).sum()
c3 = ((log_pe_te <= dpe_lo) & (log_rho_te >= drho_hi)).sum()
c4 = ((log_pe_te >= dpe_hi) & (log_rho_te >= drho_hi)).sum()
print(f"\nTest set corner coverage:")
print(f"  (low Pe, low ρ):  {c1}")
print(f"  (high Pe, low ρ): {c2}")
print(f"  (low Pe, high ρ): {c3}")
print(f"  (high Pe, high ρ): {c4}")
print(f"  Corner total: {c1+c2+c3+c4} / {len(pe_te)} test samples")

# ── 5. TRAINING (both modes) ────────────────────────────────────────────
# Uses the built-in train_multi_bubble_on_dataset which trains each
# bubble independently with value-only loss (grad_weight=0).

multi_model = MultiKANBubble1D(n_bubbles=2, n_hidden=10, n_grid=8, spline_order=3)
n_params = sum(p.numel() for p in multi_model.parameters())
print(f"MultiKANBubble1D: {n_params} params ({n_params // 2} per mode)\n")

multi_model.to(device)

print(f"CUDA: {torch.cuda.is_available()}, device: {next(multi_model.parameters()).device}")
print(f"Train samples: {len(ds['train']['constant']['pe'])}")

# ── Single-forward benchmark ──

import time, torch
model = multi_model.bubbles[0]
xi = torch.linspace(0, 1, 100, device=device)
pe = torch.full_like(xi, 10.0)
rho = torch.full_like(xi, 0.0)

# warmup
for _ in range(5): model(xi, pe, rho); torch.cuda.synchronize()

# timed
t0 = time.time()
for _ in range(50): model(xi, pe, rho); torch.cuda.synchronize()
t1 = time.time()
print(f"Single forward (100 pts): {(t1-t0)/50*1000:.1f} ms  |  {(t1-t0)/50:.4f} s")
# Expected: < 1 ms on GPU. If >5 ms, there's a kernel-launch overhead issue.


# ── Full batch benchmark (256 samples, 100 pts each) ──
BS = 256; Q = 100
xi_b = torch.linspace(0, 1, Q, device=device).unsqueeze(0).expand(BS, -1).reshape(-1)
pe_b = torch.full((BS*Q,), 10.0, device=device)
rho_b = torch.full((BS*Q,), 0.0, device=device)

# warmup
for _ in range(3): multi_model(xi_b, pe_b, rho_b); torch.cuda.synchronize()

t0 = time.time()
for _ in range(20): multi_model(xi_b, pe_b, rho_b); torch.cuda.synchronize()
t1 = time.time()
fwd_time = (t1-t0)/20
print(f"Batch forward (256×100 pts): {fwd_time*1000:.1f} ms  |  {fwd_time:.4f} s")

# fwd+bwd (loss-less, no grad term)
opt = torch.optim.Adam(multi_model.parameters(), lr=1e-3)
t0 = time.time()
for _ in range(10):
    opt.zero_grad()
    out = multi_model(xi_b, pe_b, rho_b)
    loss = out.mean()
    loss.backward()
    opt.step()
    torch.cuda.synchronize()
t1 = time.time()
step_time = (t1-t0)/10
print(f"Batch step (fwd+bwd+opt, 256×100): {step_time*1000:.1f} ms  |  {step_time:.4f} s")
print(f"Estimated for 700 epochs × 4 batches/epoch: {700*4*step_time/60:.0f} min")
# Expected: step < 20 ms → ~1 min total

histories = train_multi_bubble_on_dataset(
    multi_model, ds["train"],
    mode_names=("constant", "xi"),
    n_epochs=700, batch_size=256, lr=1e-3,
    grad_weight=0.0,   # value-only — gradient term diverges
    n_quad=100,
    verbose=True,
    device=device,
)
print("\nTraining done!")

# ── 5B. SAVE OR LOAD PRETRAINED MODEL ───────────────────────────────────
try:
    from google.colab import files
    file_name = "multi_kan_700ep_5k_frame.pt"
    torch.save(multi_model.state_dict(), file_name)
    files.download(file_name)
except ImportError:
    torch.save(multi_model.state_dict(), "models/multi_kan_700ep_5k_frame.pt")
    print("Saved to models/multi_kan_700ep_5k_frame.pt")

# To load a pretrained model:
# multi_model = MultiKANBubble1D(n_bubbles=2, n_hidden=10, n_grid=8, spline_order=3)
# multi_model.load_state_dict(torch.load('models/multi_kan_700ep_5k_frame.pt'))
# multi_model.to(device)

# ── 5C. LOSS CURVES ─────────────────────────────────────────────────────
if 'histories' in dir():
    fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True)
    for ax, (mname, hist) in zip(axes, histories.items()):
        ax.plot(hist)
        ax.set_yscale('log')
        ax.set_xlabel('epoch')
        ax.set_ylabel('MSE')
        ax.set_title(f"{mname} — final loss: {hist[-1]:.4e}")
        ax.grid(True, alpha=0.3)
    fig.tight_layout()
    plt.show()
else:
    print("Training not run — skipping loss curves.")

# ── 5D. TEST BOTH MODES ON THE FRAME (HELD-OUT TEST SET) ────────────────
xi_full_t = torch.tensor(xi_full, dtype=torch.float32, device=device)
n_fd = len(xi_full)

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
for ax_idx, (i, mname) in enumerate([(0, "constant"), (1, "xi")]):
    test_data = ds["test"][mname]
    p_te = torch.tensor(test_data["pe"], dtype=torch.float32, device=device)
    r_te = torch.tensor(test_data["rho"], dtype=torch.float32, device=device)
    n_te = p_te.shape[0]

    with torch.no_grad():
        xi_et = xi_full_t.unsqueeze(0).expand(n_te, -1).reshape(-1)
        p_et  = p_te.unsqueeze(1).expand(-1, n_fd).reshape(-1)
        r_et  = r_te.unsqueeze(1).expand(-1, n_fd).reshape(-1)
        pred = multi_model.bubbles[i](xi_et, p_et, r_et).reshape(n_te, n_fd)
        mse = F.mse_loss(pred, torch.tensor(test_data["b"], dtype=torch.float32, device=device)).item()
        rms = np.sqrt(np.mean((pred.cpu().numpy() - test_data["b"])**2, axis=1))

    # Color by corner region
    log_pe = np.log10(test_data["pe"])
    log_rho = np.log10(test_data["rho"])
    in_corner = ((log_pe <= dpe_lo) | (log_pe >= dpe_hi)) & \
                ((log_rho <= drho_lo) | (log_rho >= drho_hi))

    axes[ax_idx].scatter(test_data["pe"][~in_corner], rms[~in_corner],
                         alpha=0.4, s=10, c='steelblue', label='frame edge')
    axes[ax_idx].scatter(test_data["pe"][in_corner], rms[in_corner],
                         alpha=0.7, s=20, c='red', label='corner (extrapolation)')
    axes[ax_idx].set_xscale('log')
    axes[ax_idx].set_xlabel('Pe')
    axes[ax_idx].set_ylabel('RMSE per sample')
    axes[ax_idx].set_title(f"{mname}  —  MSE={mse:.4e}")
    axes[ax_idx].legend(fontsize=8)
    axes[ax_idx].grid(True, alpha=0.3)
fig.tight_layout()
plt.show()

# ── 6. COMPARE BUBBLE SHAPES: KAN vs EXACT (FROM CORNERS) ───────────────
# Pick samples from the 4 corners of the frame — true extrapolation test.
# The model has NEVER seen these (Pe, ρ) regimes during training.

xi_plot = np.linspace(0, 1, 201)
H = 1/16; BETA = 1.0

test_data_const = ds["test"]["constant"]
log_pe_te = np.log10(test_data_const["pe"])
log_rho_te = np.log10(test_data_const["rho"])

# Find one sample closest to each corner
def find_nearest_corner(pe_arr, rho_arr, log_pe_arr, log_rho_arr, corner_pe, corner_rho):
    dist = np.sqrt((log_pe_arr - corner_pe)**2 + (log_rho_arr - corner_rho)**2)
    return int(np.argmin(dist))

corners = {
    "low Pe, low ρ":  (dpe_lo, drho_lo),
    "high Pe, low ρ": (dpe_hi, drho_lo),
    "low Pe, high ρ": (dpe_lo, drho_hi),
    "high Pe, high ρ": (dpe_hi, drho_hi),
}

corner_idx = {}
for name, (cpe, crho) in corners.items():
    corner_idx[name] = find_nearest_corner(
        test_data_const["pe"], test_data_const["rho"],
        log_pe_te, log_rho_te, cpe, crho
    )

fig, axes = plt.subplots(4, 2, figsize=(10, 12), sharex=True, sharey='row')
for row, (corner_name, ci) in enumerate(corner_idx.items()):
    pe = test_data_const["pe"][ci]
    rho = test_data_const["rho"][ci]
    eps = BETA * H / (2 * pe)
    sigma = rho * eps / H**2

    b_kan, _ = multi_model.value_grad_numpy(xi_plot, pe, rho)

    exact = ExactRFBubbleSet1D(eps, BETA, sigma, H,
                                residual_modes=("constant", "xi"), n_points=4000)
    b_ex, _ = exact.value_grad_numpy(xi_plot, pe, rho)

    for col, (mode_name, k, e) in enumerate([("b̂ (constant)", 0, 0), ("b̃ (xi)", 1, 1)]):
        axes[row, col].plot(xi_plot, b_kan[k], label='KAN')
        axes[row, col].plot(xi_plot, b_ex[e], '--', label='Exact FD')
        axes[row, col].set_title(f"{corner_name}\n{mode_name}  Pe={pe:.2f}, ρ={rho:.2f}")
        axes[row, col].legend(fontsize=8)
        axes[row, col].grid(True, alpha=0.3)

fig.supxlabel('ξ')
fig.suptitle("Corner generalization test: KAN vs Exact (never trained on these regimes)", fontsize=12, y=1.01)
fig.tight_layout()
plt.show()

# ── 7. ASSEMBLY: classical vs KAN-RFB vs exact RFB (FROM FRAME CORNERS) ─
# Test assembly on PDEs from each corner of the frame.
# The KAN model has never seen these extreme (Pe, ρ) during training.

print("=" * 70)
print("ASSEMBLY TESTS — Frame Corner Generalization")
print("=" * 70)

for corner_name, ci in corner_idx.items():
    pe_test = test_data_const["pe"][ci]
    rho_test = test_data_const["rho"][ci]
    EPS = BETA * H / (2 * pe_test)
    SIGMA = rho_test * EPS / H**2
    N_EL = 16

    print(f"\n--- {corner_name}: Pe={pe_test:.2f}, ρ={rho_test:.2f} ---")
    print(f"    ε={EPS:.4e}, β={BETA}, σ={SIGMA:.4e}")

    mesh = Mesh1D(0.0, 1.0, N_EL)
    quad = GaussLegendre(16)
    pde = AdvectionDiffusion1D(EPS, BETA, SIGMA)
    pde.set_source_from_function(lambda x: np.ones_like(x))

    # Ground truth (fine FD)
    N_FD = 8000
    dx_ref = 1.0 / (N_FD - 1)
    x_ref = np.linspace(0, 1, N_FD)
    A_ref = np.zeros((N_FD, N_FD))
    rhs_ref = np.ones(N_FD)
    for j in range(1, N_FD - 1):
        A_ref[j, j-1] = -EPS/dx_ref**2 - BETA/(2*dx_ref)
        A_ref[j, j]   =  2*EPS/dx_ref**2 + SIGMA
        A_ref[j, j+1] = -EPS/dx_ref**2 + BETA/(2*dx_ref)
    A_ref[0,0] = A_ref[-1,-1] = 1.0
    rhs_ref[0] = rhs_ref[-1] = 0.0
    u_exact = np.linalg.solve(A_ref, rhs_ref)

    def exact_u(x): return np.interp(x, x_ref, u_exact)

    # Classical P1
    A_cl, F_cl = assemble_classical_system(mesh, quad, pde)
    u_cl = np.linalg.solve(A_cl, F_cl)

    class ClassicalSolution:
        def __init__(self, mesh, u):
            self.mesh = mesh; self.u = u
        def __call__(self, x):
            basis = LagrangeBasis1D(self.mesh)
            out = np.zeros_like(x)
            for ni in range(self.mesh.n_nodes):
                out += self.u[ni] * basis.eval(x, ni)
            return out

    l2_cl, norm = compute_l2_error(ClassicalSolution(mesh, u_cl), exact_u)

    # Exact RFB
    exact_set = ExactRFBubbleSet1D(EPS, BETA, SIGMA, mesh.h,
                                    residual_modes=("constant", "xi"), n_points=8000)
    A_ex, F_ex, local_ex = assemble_rfb_condensed_system(mesh, quad, pde, exact_set)
    u_ex = np.linalg.solve(A_ex, F_ex)
    ub_ex = recover_bubble_coefficients(u_ex, mesh, local_ex)
    sol_ex = RFBSolution1D(u_ex, ub_ex, mesh, exact_set, pde)
    l2_ex, _ = compute_l2_error(sol_ex, exact_u)

    # KAN-RFB
    A_kan, F_kan, local_kan = assemble_rfb_condensed_system(mesh, quad, pde, multi_model)
    u_kan = np.linalg.solve(A_kan, F_kan)
    ub_kan = recover_bubble_coefficients(u_kan, mesh, local_kan)
    sol_kan = RFBSolution1D(u_kan, ub_kan, mesh, multi_model, pde)
    l2_kan, _ = compute_l2_error(sol_kan, exact_u)

    print(f"    {'Method':<20} {'L2 error':<12} {'Rel %':<8}")
    print(f"    {'-'*20} {'-'*12} {'-'*8}")
    for name, err in [("Classical P1", l2_cl), ("Exact RFB", l2_ex), ("KAN-RFB", l2_kan)]:
        print(f"    {name:<20} {err:<12.4e} {relative_error_percentage(err, norm):<8.1f}")

# ── 8. CORNER GENERALIZATION SUMMARY ────────────────────────────────────
print("\n" + "=" * 70)
print("CORNER GENERALIZATION SUMMARY")
print("=" * 70)
print("The test set covers 4 corners of the (log-Pe, log-ρ) rectangle")
print("that the model has NEVER seen during training.")
print("If KAN-RFB errors remain close to Exact RFB in these corners,")
print("the model has learned a truly generalizable bubble representation.\n")

# Compute per-corner MSE for both modes
for corner_name, ci in corner_idx.items():
    pe_val = test_data_const["pe"][ci]
    rho_val = test_data_const["rho"][ci]
    eps_val = BETA * H / (2 * pe_val)
    sigma_val = rho_val * eps_val / H**2

    xi_t = torch.tensor(xi_plot, dtype=torch.float32, device=device)
    pe_t = torch.full_like(xi_t, pe_val)
    rho_t = torch.full_like(xi_t, rho_val)

    kan_pred = multi_model.value_grad_numpy(xi_plot, pe_val, rho_val)

    exact = ExactRFBubbleSet1D(eps_val, BETA, sigma_val, H,
                                residual_modes=("constant", "xi"), n_points=4000)
    exact_pred = exact.value_grad_numpy(xi_plot, pe_val, rho_val)

    for mode_i, mode_name in enumerate(["b̂ (constant)", "b̃ (xi)"]):
        mse_kan = np.mean((kan_pred[mode_i] - exact_pred[mode_i])**2)
        print(f"  {corner_name:20s} | {mode_name:12s} | MSE(KAN vs Exact) = {mse_kan:.4e}")

# ── 9. PLOT SOLUTIONS AT EACH CORNER ────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(12, 8), sharex=True, sharey=True)
x_p = np.linspace(0, 1, 300)
N_EL = 16

for ax, (corner_name, ci) in zip(axes.flat, corner_idx.items()):
    pe_val = test_data_const["pe"][ci]
    rho_val = test_data_const["rho"][ci]
    EPS = BETA * H / (2 * pe_val)
    SIGMA = rho_val * EPS / H**2

    mesh = Mesh1D(0.0, 1.0, N_EL)
    quad = GaussLegendre(16)
    pde = AdvectionDiffusion1D(EPS, BETA, SIGMA)
    pde.set_source_from_function(lambda x: np.ones_like(x))

    # Fine FD reference
    N_FD = 8000
    dx_ref = 1.0 / (N_FD - 1)
    x_ref = np.linspace(0, 1, N_FD)
    A_ref = np.zeros((N_FD, N_FD))
    rhs_ref = np.ones(N_FD)
    for j in range(1, N_FD - 1):
        A_ref[j, j-1] = -EPS/dx_ref**2 - BETA/(2*dx_ref)
        A_ref[j, j]   =  2*EPS/dx_ref**2 + SIGMA
        A_ref[j, j+1] = -EPS/dx_ref**2 + BETA/(2*dx_ref)
    A_ref[0,0] = A_ref[-1,-1] = 1.0
    rhs_ref[0] = rhs_ref[-1] = 0.0
    u_ref = np.linalg.solve(A_ref, rhs_ref)

    # Classical P1
    A_cl, F_cl = assemble_classical_system(mesh, quad, pde)
    u_cl = np.linalg.solve(A_cl, F_cl)

    class ClassicalSol:
        def __init__(self, m, u): self.mesh = m; self.u = u
        def __call__(self, x):
            b = LagrangeBasis1D(self.mesh)
            return sum(self.u[i] * b.eval(x, i) for i in range(self.mesh.n_nodes))

    # Exact RFB
    exact_set = ExactRFBubbleSet1D(EPS, BETA, SIGMA, mesh.h,
                                    residual_modes=("constant", "xi"), n_points=8000)
    A_ex, F_ex, local_ex = assemble_rfb_condensed_system(mesh, quad, pde, exact_set)
    u_ex = np.linalg.solve(A_ex, F_ex)
    ub_ex = recover_bubble_coefficients(u_ex, mesh, local_ex)
    sol_ex = RFBSolution1D(u_ex, ub_ex, mesh, exact_set, pde)

    # KAN-RFB
    A_kan, F_kan, local_kan = assemble_rfb_condensed_system(mesh, quad, pde, multi_model)
    u_kan = np.linalg.solve(A_kan, F_kan)
    ub_kan = recover_bubble_coefficients(u_kan, mesh, local_kan)
    sol_kan = RFBSolution1D(u_kan, ub_kan, mesh, multi_model, pde)

    ax.plot(x_ref, np.interp(x_p, x_ref, u_ref), 'k-', lw=1.5, label='Exact FD')
    ax.plot(x_p, ClassicalSol(mesh, u_cl)(x_p), '--', label='Classical P1')
    ax.plot(x_p, sol_ex(x_p), ':', lw=2, label='Exact RFB')
    ax.plot(x_p, sol_kan(x_p), '-.', lw=2, label='KAN-RFB')
    ax.set_title(f"{corner_name}\nPe={pe_val:.1f}, ρ={rho_val:.1f}", fontsize=10)
    ax.grid(True, alpha=0.3)

axes[0, 0].legend(fontsize=8)
fig.supxlabel('x')
fig.sup_ylabel('u(x)')
fig.suptitle("PDE solutions at frame corners (never trained on these regimes)", fontsize=12, y=1.01)
fig.tight_layout()
plt.show()
