# -*- coding: utf-8 -*-
"""tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dn7G7rt3qbTIqf5o7LGpbvWsSYDGRR6U

# KAN-RFB Code Using — import, data, visualize, train, test

Demonstrates the full pipeline: loading data, plotting bubble shapes,
training both modes (constant & xi) via `train_multi_bubble_on_dataset`,
and testing in the static-condensation assembly.

---
## Colab setup
Run this cell first if using Google Colab (otherwise skip it).
"""



# ── 0. COLAB SETUP (run first if using Colab) ─────────────────────────────
import os, torch
if os.path.isdir('/content') and not os.path.isdir('/content/ML_Galerkin_proj'):
    os.system('git clone https://github.com/juanpaca/ML_Galerkin_proj.git /content/ML_Galerkin_proj')
if os.path.isdir('/content/ML_Galerkin_proj'):
    os.system('git -C /content/ML_Galerkin_proj pull')

# Mount Google Drive and symlink datasets (too large for git)
if os.path.isdir('/content'):
    try:
        from google.colab import drive
        drive.mount('/content/drive')
        # Upload your datasets/ folder to Google Drive/ML_Galerkin_proj/datasets/ first
        os.system('rm -rf /content/ML_Galerkin_proj/datasets')
        os.system('ln -s "/content/drive/MyDrive/ML_Galerkin_proj/datasets" /content/ML_Galerkin_proj/datasets')
        print("Datasets loaded from Google Drive")
    except ImportError:
        print("Not on Colab — using local datasets/")

# ── 1. IMPORTS ──────────────────────────────────────────────────────────
import sys, os
# In Colab, CWD is /content; in local, it's the project root
if os.path.isdir('/content/ML_Galerkin_proj'):
    sys.path.insert(0, '/content/ML_Galerkin_proj')
else:
    sys.path.insert(0, '.')

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

from src.dataset_generation import (
    load_dataset, dataset_summary, train_multi_bubble_on_dataset,
    bubble_similarity_analysis,
)
from src.rfb_bubble import KANBubble1D, MultiKANBubble1D
from src.rfb_exact import ExactRFBubbleSet1D
from src.rfb_assembly import (
    assemble_classical_system, assemble_rfb_condensed_system,
    recover_bubble_coefficients, RFBSolution1D,
)
from src.mesh import Mesh1D
from src.quadrature import GaussLegendre
from src.pde import AdvectionDiffusion1D
from src.basis import LagrangeBasis1D
from src.errors import compute_l2_error, relative_error_percentage

# Move training to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

def sync():
    if torch.cuda.is_available():
        torch.cuda.synchronize()

# ── 2. LOAD DATASET ─────────────────────────────────────────────────────
ds = load_dataset("/content/drive/MyDrive/datasets/rfb_5k_noleak")
dataset_summary(ds)

# Dataset structure (shape-split, no-twin):
#   ds["train"]["constant"]  →  {pe, rho, xi, b, db}  — diffusion bubbles, Pe≈2.3–16.7
#   ds["val"][...]           →  transition Pe band
#   ds["test"][...]          →  boundary-layer bubbles, Pe≈51–100 (OOD by design)
#
# The split is NOT a (Pe, ρ) box: it is made in *function space*. Bubbles are
# grouped by shape similarity and the no-twin constraint guarantees that no
# test bubble has a near-duplicate (similarity > 0.99) in the training set.

xi_full = ds["train"]["constant"]["xi"]  # original FD grid
print(f"xi grid: {xi_full.shape[0]} points")
print(f"n_fd_points = {ds['metadata']['n_fd_points']}, "
      f"split_strategy = {ds['metadata']['split_strategy']}, "
      f"theta = {ds['metadata'].get('similarity_theta')}")

# ── 2B. SIMILARITY ANALYSIS — CONFIRMING THE SPLIT IS LEAK-FREE ────────────
# concern: if the bubbles are functionally redundant (near-
# duplicate shapes), the KAN can memorize a single function and still report
# low test error — the *effective* number of distinct shapes in the dataset
# may be far smaller than the number of samples, inflating generalization
# numbers. We quantify this with derivative-aware H1 cosine similarities:
#
#   C[i,j] = <b_i, b_j>_H1 / (||b_i||_H1 ||b_j||_H1),   C=1 => identical shape
#   <b_i,b_j>_H1 = int b_i b_j + lambda^2 * int b_i' b_j'   (default lambda=0.2)
#
# The H1 inner product includes the *changes* of the functions: two bubbles
# that differ in boundary-layer sharpness or oscillation are NOT considered
# near-duplicates even when their L2 mass overlaps. Then, for each test
# bubble, its *best* similarity to any training bubble is computed
# (function-space leakage: a test bubble with a train twin C>0.99 is not a
# genuine OOD benchmark). We run the analysis on BOTH the old frame-split
# dataset (which leaks) and the new no-leak dataset (which should not).

# Load the old frame dataset for comparison (also shipped in datasets/)
ds_frame = load_dataset("/content/drive/MyDrive/datasets/rfb_5k_frame")

res_noleak = bubble_similarity_analysis(ds,        mode="constant",
                                        return_matrices=True, verbose=False)
res_frame  = bubble_similarity_analysis(ds_frame,  mode="constant",
                                        return_matrices=True, verbose=False)

nl = res_noleak["cross"]["train_vs_test"]
fr = res_frame["cross"]["train_vs_test"]

fig, axes = plt.subplots(2, 2, figsize=(13, 9))

# Left column: train-vs-test similarity heatmaps (rows = test, cols = train,
# both sorted by Pe). Frame: every test bubble is near-identical to a train
# bubble → solid red rows. No-leak: no row reaches the 0.99 twin threshold.
def sorted_heatmap(C, row_pe, col_pe, ax, title, max_rows=200, max_cols=250):
    Cr = C[np.ix_(np.argsort(row_pe), np.argsort(col_pe))]
    r_idx = np.linspace(0, Cr.shape[0] - 1, min(max_rows, Cr.shape[0])).astype(int)
    c_idx = np.linspace(0, Cr.shape[1] - 1, min(max_cols, Cr.shape[1])).astype(int)
    im = ax.imshow(Cr[np.ix_(r_idx, c_idx)], aspect='auto', cmap='Reds',
                   vmin=0.90, vmax=1.0)
    ax.set_title(title, fontsize=10)
    ax.set_xlabel("train samples (sorted by Pe)")
    ax.set_ylabel("test samples (sorted by Pe)")
    ax.grid(False)
    return im

im = sorted_heatmap(fr["C"], ds_frame["test"]["constant"]["pe"],
                    ds_frame["train"]["constant"]["pe"], axes[0, 0],
                    f"FRAME split — {100*fr['stats']['frac_gt_0.99']:.0f}% of test "
                    f"bubbles have a train twin (C>0.99)")
fig.colorbar(im, ax=axes[0, 0], label="max train-test similarity")

im = sorted_heatmap(nl["C"], ds["test"]["constant"]["pe"],
                    ds["train"]["constant"]["pe"], axes[0, 1],
                    f"NO-LEAK split — {100*nl['stats']['frac_gt_0.99']:.0f}% of test "
                    f"bubbles have a train twin (C>0.99)")
fig.colorbar(im, ax=axes[0, 1], label="max train-test similarity")

# Bottom-left: histogram of each test bubble's best similarity to ANY train
# bubble. Frame peaks at 1.0 (leak); no-leak peaks below 0.99 (genuine OOD).
bins = np.linspace(0.90, 1.0, 50)
axes[1, 0].hist(fr["max_similarity"], bins=bins, alpha=0.5, color='red',
                label=f"frame (leaks): {100*fr['stats']['frac_gt_0.99']:.0f}% twins")
axes[1, 0].hist(nl["max_similarity"], bins=bins, alpha=0.5, color='steelblue',
                label=f"no-leak: {100*nl['stats']['frac_gt_0.99']:.0f}% twins")
axes[1, 0].axvline(0.99, color='k', ls='--', label="twin threshold θ=0.99")
axes[1, 0].set_xlabel("best similarity of each test bubble to any train bubble")
axes[1, 0].set_ylabel("number of test bubbles")
axes[1, 0].set_title("Function-space leakage: frame vs no-leak split")
axes[1, 0].legend(fontsize=8)
axes[1, 0].grid(True, alpha=0.3)

# Bottom-right: twin rate and within-train redundancy.
fracs  = [100*fr['stats']['frac_gt_0.99'], 100*nl['stats']['frac_gt_0.99']]
effrk  = [res_frame['within']['train']['effective_rank']['effective_rank'],
          res_noleak['within']['train']['effective_rank']['effective_rank']]
x = np.arange(2)
axes[1, 1].bar(x, fracs, width=0.4, color=['red', 'steelblue'], alpha=0.8,
               tick_label=['frame', 'no-leak'])
axes[1, 1].set_ylabel("% of test bubbles with a train twin (C>0.99)")
axes[1, 1].set_title("Twin rate (test)  |  train eff. rank: "
                     f"{effrk[0]:.2f} vs {effrk[1]:.2f}", fontsize=10)
axes[1, 1].axhline(0, color='k', lw=1)
for i, f in enumerate(fracs):
    axes[1, 1].text(i, f + 1, f"{f:.0f}%", ha='center', fontweight='bold')
axes[1, 1].set_ylim(0, 110)
axes[1, 1].grid(True, alpha=0.3, axis="y")

fig.tight_layout()
plt.show()

# ── Verdict ──
leak_frame = res_frame["cross"]["train_vs_test"]["stats"]
leak_noleak = res_noleak["cross"]["train_vs_test"]["stats"]
er_frame = res_frame["within"]["train"]["effective_rank"]
er_noleak = res_noleak["within"]["train"]["effective_rank"]

print("=" * 72)
print("  LEAKAGE VERDICT")
print("=" * 72)
print(f"  FRAME split:  {100*leak_frame['frac_gt_0.99']:.1f}% of test bubbles have a"
      f" train twin (max-sim mean {leak_frame['max_sim_mean']:.4f})")
print(f"    → the frame test set is NOT a genuine OOD benchmark: it leaks.")
print(f"    → train effective rank {er_frame['effective_rank']:.2f} of "
      f"{res_frame['within']['train']['n_samples']} samples (heavily redundant).")
print()
print(f"  NO-LEAK split: {100*leak_noleak['frac_gt_0.99']:.1f}% twins; best train-test"
      f" sim ∈ [{leak_noleak['max_sim_min']:.4f}, {leak_noleak['max_sim_max']:.4f}]")
print(f"    → every test bubble is a genuinely new shape: OOD by construction.")
print(f"    → train effective rank {er_noleak['effective_rank']:.2f} (train is still a")
print(f"       single Pe band, but it no longer contains the test shapes).")
print("=" * 72)
print("""Reading: both datasets are redundant WITHIN the training band (one
diffusion shape family), but only the no-leak split keeps the test set free
of training twins. Low test error on rfb_5k_noleak is therefore earned by
interpolating in (Pe, ρ) → extrapolating the bubble into the boundary-layer
regime, not by memorizing near-duplicate shapes.""")

# ── 3. VISUALIZE BUBBLE SHAPES: LOW Pe (TRAIN) vs HIGH Pe (TEST) ───────────
# Low-Pe bubbles (diffusion-dominated) are rounded and nearly symmetric;
# high-Pe bubbles (advection-dominated) develop a sharp boundary layer at
# ξ=1. The no-leak test set is exactly the latter — the model must learn the
# Pe↦shape map well enough to extrapolate into this regime.

train_idx = np.argsort(ds["train"]["constant"]["pe"])[:3]   # lowest-Pe train bubbles
test_idx  = np.argsort(ds["test"]["constant"]["pe"])[-3:]   # highest-Pe test bubbles

fig, axes = plt.subplots(2, 3, figsize=(14, 7), sharex=True, sharey=True)
for col, (ti, ei) in enumerate(zip(train_idx, test_idx)):
    for row, (label, split, i) in enumerate([
            ("train — diffusion", "train", ti),
            ("test  — boundary layer", "test", ei)]):
        ax = axes[row, col]
        pe = ds[split]["constant"]["pe"][i]
        rho = ds[split]["constant"]["rho"][i]
        ax.plot(xi_full, ds[split]["constant"]["b"][i], label="b̂ (constant)")
        ax.plot(xi_full, ds[split]["xi"]["b"][i], '--', label="b̃ (xi)")
        ax.set_title(f"{label}\nPe={pe:.2f}, ρ={rho:.2f}", fontsize=9)
        ax.grid(True, alpha=0.3)
        if row == 0:
            ax.legend(fontsize=7)
fig.supxlabel("ξ")
fig.supylabel("bubble shape b̂(ξ), b̃(ξ)")
fig.suptitle("Low-Pe train bubbles (rounded, symmetric) vs high-Pe test bubbles "
             "(boundary layer at ξ=1) — the model must extrapolate in Pe",
             fontsize=11, y=1.01)
fig.tight_layout()
plt.show()

# ── 4. VISUALIZE THE SPLIT & CHECK NO LEAKAGE ─────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
colors = {"train": "#1F4E79", "val": "#F7DC6F", "test": "#E74C3C"}

# Left: log(Pe) vs log(rho) scatter with Pe bands of train/test.
# The no-twin shape split is (in log-Pe x log-rho space) an axis-aligned
# holdout in Pe: train = diffusion band, test = high-Pe band. ρ is fully
# shared between splits (the bubble depends on ρ only through the reaction).
for sname in ["train", "val", "test"]:
    pe_s = ds[sname]["constant"]["pe"]
    rho_s = ds[sname]["constant"]["rho"]
    axes[0].scatter(np.log10(pe_s), np.log10(rho_s),
                    c=colors[sname], alpha=0.3, s=8, label=sname, edgecolors='none')

train_pe_lo, train_pe_hi = ds["train"]["constant"]["pe"].min(), ds["train"]["constant"]["pe"].max()
test_pe_lo,  test_pe_hi  = ds["test"]["constant"]["pe"].min(),  ds["test"]["constant"]["pe"].max()
axes[0].axvspan(np.log10(train_pe_lo), np.log10(train_pe_hi),
                color='#1F4E79', alpha=0.08)
axes[0].axvspan(np.log10(test_pe_lo), np.log10(test_pe_hi),
                color='#E74C3C', alpha=0.08)
axes[0].axvline(np.log10(train_pe_hi), color='#1F4E79', ls=':', lw=1.5)
axes[0].axvline(np.log10(test_pe_lo), color='#E74C3C', ls=':', lw=1.5)
axes[0].text(np.log10(train_pe_lo) + 0.02, 1.9, f"train Pe\n[{train_pe_lo:.1f},{train_pe_hi:.1f}]",
             fontsize=8, color='#1F4E79')
axes[0].text(np.log10(test_pe_lo) - 0.02, 1.9, f"test Pe\n[{test_pe_lo:.1f},{test_pe_hi:.1f}]",
             fontsize=8, color='#E74C3C', ha='right')

axes[0].set_xlabel("log₁₀(Pe)")
axes[0].set_ylabel("log₁₀(ρ)")
axes[0].set_title("Shape split (no-twin): test = high-Pe boundary-layer band")
axes[0].legend(fontsize=9)
axes[0].grid(True, alpha=0.3)

# Right: sample counts per split
split_names = ["train", "val", "test"]
counts = [len(ds[s]["constant"]["pe"]) for s in split_names]
bar_colors = [colors[s] for s in split_names]
axes[1].bar(split_names, counts, color=bar_colors, alpha=0.8, edgecolor='black')
axes[1].set_ylabel("Number of samples")
axes[1].set_title(f"Shape split: {counts[0]}tr / {counts[1]}va / {counts[2]}te")
for i, c in enumerate(counts):
    axes[1].text(i, c + 20, str(c), ha='center', fontweight='bold')
axes[1].grid(True, alpha=0.3, axis="y")

plt.tight_layout()
plt.show()

# Verify: no sample overlap between splits
train_ids = set(ds["metadata"]["split_indices"]["train"])
val_ids   = set(ds["metadata"]["split_indices"]["val"])
test_ids  = set(ds["metadata"]["split_indices"]["test"])
print(f"Samples: {len(train_ids)} train / {len(val_ids)} val / {len(test_ids)} test")
print(f"Overlap train∩val: {len(train_ids & val_ids)}")
print(f"Overlap train∩test: {len(train_ids & test_ids)}")
print(f"Overlap val∩test: {len(val_ids & test_ids)}")
print("→ No leakage" if not (train_ids & val_ids or train_ids & test_ids or val_ids & test_ids) else "→ LEAKAGE DETECTED!")

# Pe-range table per split (this is the OOD mechanism for the test set)
print(f"\nPe range per split (log-uniform pool, Pe ∈ [{ds['metadata']['pe_range'][0]}, "
      f"{ds['metadata']['pe_range'][1]}])")
print(f"  {'split':<8}{'min':>10}{'median':>10}{'max':>10}{'count':>8}")
for s in split_names:
    pe_s = ds[s]["constant"]["pe"]
    print(f"  {s:<8}{pe_s.min():>10.3f}{np.median(pe_s):>10.3f}{pe_s.max():>10.3f}{len(pe_s):>8}")

# ── 5. TRAINING (both modes) ────────────────────────────────────────────
# Uses the built-in train_multi_bubble_on_dataset which trains each
# bubble independently with value-only loss (grad_weight=0).

multi_model = MultiKANBubble1D(n_bubbles=2, n_hidden=10, n_grid=8, spline_order=3)
n_params = sum(p.numel() for p in multi_model.parameters())
print(f"MultiKANBubble1D: {n_params} params ({n_params // 2} per mode)\n")

multi_model.to(device)

print(f"CUDA: {torch.cuda.is_available()}, device: {next(multi_model.parameters()).device}")
print(f"Train samples: {len(ds['train']['constant']['pe'])}")

# ── Single-forward benchmark ──

import time, torch
model = multi_model.bubbles[0]
xi = torch.linspace(0, 1, 100, device=device)
pe = torch.full_like(xi, 10.0)
rho = torch.full_like(xi, 0.0)

# warmup
for _ in range(5):
    model(xi, pe, rho)
    sync()

# timed
t0 = time.time()
for _ in range(50):
    model(xi, pe, rho)
    sync()
t1 = time.time()
print(f"Single forward (100 pts): {(t1-t0)/50*1000:.1f} ms  |  {(t1-t0)/50:.4f} s")
# Expected: < 1 ms on GPU. If >5 ms, there's a kernel-launch overhead issue.


# ── Full batch benchmark (256 samples, 100 pts each) ──
BS = 256; Q = 100
xi_b = torch.linspace(0, 1, Q, device=device).unsqueeze(0).expand(BS, -1).reshape(-1)
pe_b = torch.full((BS*Q,), 10.0, device=device)
rho_b = torch.full((BS*Q,), 0.0, device=device)

# warmup
for _ in range(3):
    multi_model(xi_b, pe_b, rho_b)
    sync()

t0 = time.time()
for _ in range(20):
    multi_model(xi_b, pe_b, rho_b)
    sync()
t1 = time.time()
fwd_time = (t1-t0)/20
print(f"Batch forward (256×100 pts): {fwd_time*1000:.1f} ms  |  {fwd_time:.4f} s")

# fwd+bwd (loss-less, no grad term)
opt = torch.optim.Adam(multi_model.parameters(), lr=1e-3)
t0 = time.time()
for _ in range(10):
    opt.zero_grad()
    out = multi_model(xi_b, pe_b, rho_b)
    loss = out.mean()
    loss.backward()
    opt.step()
    sync()
t1 = time.time()
step_time = (t1-t0)/10
print(f"Batch step (fwd+bwd+opt, 256×100): {step_time*1000:.1f} ms  |  {step_time:.4f} s")
print(f"Estimated for 700 epochs × 4 batches/epoch: {700*4*step_time/60:.0f} min")
# Expected: step < 20 ms → ~1 min total

histories = train_multi_bubble_on_dataset(
    multi_model, ds["train"],
    mode_names=("constant", "xi"),
    n_epochs=700, batch_size=256, lr=1e-3,
    grad_weight=0.0,   # value-only — gradient term diverges
    n_quad=100,
    verbose=True,
    device=device,
)
print("\nTraining done!")

# ── 5B. SAVE OR LOAD PRETRAINED MODEL ───────────────────────────────────
try:
    from google.colab import files
    file_name = "multi_kan_700ep_5k_noleak.pt"
    torch.save(multi_model.state_dict(), file_name)
    files.download(file_name)
except ImportError:
    os.makedirs("models", exist_ok=True)
    torch.save(multi_model.state_dict(), "models/multi_kan_700ep_5k_noleak.pt")
    print("Saved to models/multi_kan_700ep_5k_noleak.pt")

# To load a pretrained model:
# multi_model = MultiKANBubble1D(n_bubbles=2, n_hidden=10, n_grid=8, spline_order=3)
# multi_model.load_state_dict(torch.load('models/multi_kan_700ep_5k_noleak.pt'))
# multi_model.to(device)



# ── 5C. LOSS CURVES ─────────────────────────────────────────────────────
if 'histories' in dir():
    fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True)
    for ax, (mname, hist) in zip(axes, histories.items()):
        ax.plot(hist)
        ax.set_yscale('log')
        ax.set_xlabel('epoch')
        ax.set_ylabel('MSE')
        ax.set_title(f"{mname} — final loss: {hist[-1]:.4e}")
        ax.grid(True, alpha=0.3)
    fig.tight_layout()
    plt.show()
else:
    print("Training not run — skipping loss curves.")

# ── 5D. TEST BOTH MODES ON THE HELD-OUT (OOD) TEST SET ───────────────────
# Every test bubble is extrapolation: Pe ∈ [51, 100] vs train Pe ≤ 16.7.
xi_full_t = torch.tensor(xi_full, dtype=torch.float32, device=device)
n_fd = len(xi_full)

fig, axes = plt.subplots(1, 2, figsize=(11, 4.5))
for ax_idx, (i, mname) in enumerate([(0, "constant"), (1, "xi")]):
    test_data = ds["test"][mname]
    p_te = torch.tensor(test_data["pe"], dtype=torch.float32, device=device)
    r_te = torch.tensor(test_data["rho"], dtype=torch.float32, device=device)
    n_te = p_te.shape[0]

    with torch.no_grad():
        xi_et = xi_full_t.unsqueeze(0).expand(n_te, -1).reshape(-1)
        p_et  = p_te.unsqueeze(1).expand(-1, n_fd).reshape(-1)
        r_et  = r_te.unsqueeze(1).expand(-1, n_fd).reshape(-1)
        pred = multi_model.bubbles[i](xi_et, p_et, r_et).reshape(n_te, n_fd)
        mse = F.mse_loss(pred, torch.tensor(test_data["b"], dtype=torch.float32,
                                            device=device)).item()
        rms = np.sqrt(np.mean((pred.cpu().numpy() - test_data["b"])**2, axis=1))

    # Color by ρ; shade the Pe band the model trained on (everything else is OOD)
    sc = axes[ax_idx].scatter(test_data["pe"], rms, c=np.log10(test_data["rho"]),
                              alpha=0.7, s=12, cmap='viridis')
    axes[ax_idx].axvspan(train_pe_lo, train_pe_hi, color='#1F4E79', alpha=0.12,
                         label=f"train Pe ∈ [{train_pe_lo:.1f}, {train_pe_hi:.1f}]")
    axes[ax_idx].axvline(test_pe_lo, color='#E74C3C', ls=':', lw=1.5,
                         label=f"test starts at Pe={test_pe_lo:.0f}")
    axes[ax_idx].set_xscale('log')
    axes[ax_idx].set_xlabel('Pe')
    axes[ax_idx].set_ylabel('RMSE per sample')
    axes[ax_idx].set_title(f"{mname}  —  MSE={mse:.4e}")
    axes[ax_idx].legend(fontsize=8)
    axes[ax_idx].grid(True, alpha=0.3)
    fig.colorbar(sc, ax=axes[ax_idx], label='log₁₀(ρ)')
fig.suptitle("Test on the OOD boundary-layer set (Pe 51–100, never seen during training)",
             fontsize=11)
fig.tight_layout()
plt.show()

# ── 6. COMPARE BUBBLE SHAPES: KAN vs EXACT (INTERP + EXTRAP SAMPLES) ─────
# Representative samples: 2 from the train band (interpolation — the model
# has seen this regime) and 2 from the test band (extrapolation into the
# boundary-layer regime — never seen).

def closest_sample(split, log_pe_t, log_rho_t):
    data = ds[split]["constant"]
    dist = (np.log10(data["pe"]) - log_pe_t)**2 + (np.log10(data["rho"]) - log_rho_t)**2
    return int(np.argmin(dist))

rep_targets = [
    ("train", np.log10(4.0),  np.log10(1.0),  "interp — low Pe"),
    ("train", np.log10(10.0), np.log10(30.0), "interp — mid Pe"),
    ("test",  np.log10(55.0), np.log10(2.0),  "extrap — Pe≈55"),
    ("test",  np.log10(95.0), np.log10(50.0), "extrap — Pe≈95"),
]
rep_samples = []
for split, lpe, lrho, tag in rep_targets:
    i = closest_sample(split, lpe, lrho)
    rep_samples.append(dict(name=tag, split=split, idx=i,
                            pe=float(ds[split]["constant"]["pe"][i]),
                            rho=float(ds[split]["constant"]["rho"][i])))

xi_plot = np.linspace(0, 1, 201)
H = 1/16; BETA = 1.0

fig, axes = plt.subplots(4, 2, figsize=(10, 12), sharex=True, sharey='row')
for row, rp in enumerate(rep_samples):
    pe, rho = rp["pe"], rp["rho"]
    eps = BETA * H / (2 * pe)
    sigma = rho * eps / H**2

    b_kan, _ = multi_model.value_grad_numpy(xi_plot, pe, rho)

    exact = ExactRFBubbleSet1D(eps, BETA, sigma, H,
                               residual_modes=("constant", "xi"), n_points=4000)
    b_ex, _ = exact.value_grad_numpy(xi_plot, pe, rho)

    for col, (mode_name, k) in enumerate([("b̂ (constant)", 0), ("b̃ (xi)", 1)]):
        axes[row, col].plot(xi_plot, b_kan[k], label='KAN')
        axes[row, col].plot(xi_plot, b_ex[k], '--', label='Exact FD')
        axes[row, col].set_title(f"{rp['name']} — {mode_name}\nPe={pe:.2f}, ρ={rho:.2f} "
                                 f"({rp['split']})", fontsize=10)
        axes[row, col].legend(fontsize=8)
        axes[row, col].grid(True, alpha=0.3)

fig.supxlabel('ξ')
fig.suptitle("KAN vs Exact bubble shapes: train-band interpolation (rows 1–2) and "
             "OOD boundary-layer extrapolation (rows 3–4)", fontsize=12, y=1.01)
fig.tight_layout()
plt.show()

# ── 7. ASSEMBLY: classical vs KAN-RFB vs exact RFB (INTERP + EXTRAP) ──────
# Solve the full PDE with static condensation for each representative sample.

print("=" * 70)
print("ASSEMBLY TESTS — train-band interpolation vs OOD extrapolation")
print("=" * 70)

for rp in rep_samples:
    pe_test = rp["pe"]
    rho_test = rp["rho"]
    EPS = BETA * H / (2 * pe_test)
    SIGMA = rho_test * EPS / H**2
    N_EL = 16

    print(f"\n--- {rp['name']} ({rp['split']}): Pe={pe_test:.2f}, ρ={rho_test:.2f} ---")
    print(f"    ε={EPS:.4e}, β={BETA}, σ={SIGMA:.4e}")

    mesh = Mesh1D(0.0, 1.0, N_EL)
    quad = GaussLegendre(16)
    pde = AdvectionDiffusion1D(EPS, BETA, SIGMA)
    pde.set_source_from_function(lambda x: np.ones_like(x))

    # Ground truth (fine FD)
    N_FD = 8000
    dx_ref = 1.0 / (N_FD - 1)
    x_ref = np.linspace(0, 1, N_FD)
    A_ref = np.zeros((N_FD, N_FD))
    rhs_ref = np.ones(N_FD)
    for j in range(1, N_FD - 1):
        A_ref[j, j-1] = -EPS/dx_ref**2 - BETA/(2*dx_ref)
        A_ref[j, j]   =  2*EPS/dx_ref**2 + SIGMA
        A_ref[j, j+1] = -EPS/dx_ref**2 + BETA/(2*dx_ref)
    A_ref[0,0] = A_ref[-1,-1] = 1.0
    rhs_ref[0] = rhs_ref[-1] = 0.0
    u_exact = np.linalg.solve(A_ref, rhs_ref)

    def exact_u(x): return np.interp(x, x_ref, u_exact)

    # Classical P1
    A_cl, F_cl = assemble_classical_system(mesh, quad, pde)
    u_cl = np.linalg.solve(A_cl, F_cl)

    class ClassicalSolution:
        def __init__(self, mesh, u):
            self.mesh = mesh; self.u = u
        def __call__(self, x):
            basis = LagrangeBasis1D(self.mesh)
            out = np.zeros_like(x)
            for ni in range(self.mesh.n_nodes):
                out += self.u[ni] * basis.eval(x, ni)
            return out

    l2_cl, norm = compute_l2_error(ClassicalSolution(mesh, u_cl), exact_u)

    # Exact RFB
    exact_set = ExactRFBubbleSet1D(EPS, BETA, SIGMA, mesh.h,
                                   residual_modes=("constant", "xi"), n_points=8000)
    A_ex, F_ex, local_ex = assemble_rfb_condensed_system(mesh, quad, pde, exact_set)
    u_ex = np.linalg.solve(A_ex, F_ex)
    ub_ex = recover_bubble_coefficients(u_ex, mesh, local_ex)
    sol_ex = RFBSolution1D(u_ex, ub_ex, mesh, exact_set, pde)
    l2_ex, _ = compute_l2_error(sol_ex, exact_u)

    # KAN-RFB
    A_kan, F_kan, local_kan = assemble_rfb_condensed_system(mesh, quad, pde, multi_model)
    u_kan = np.linalg.solve(A_kan, F_kan)
    ub_kan = recover_bubble_coefficients(u_kan, mesh, local_kan)
    sol_kan = RFBSolution1D(u_kan, ub_kan, mesh, multi_model, pde)
    l2_kan, _ = compute_l2_error(sol_kan, exact_u)

    print(f"    {'Method':<20} {'L2 error':<12} {'Rel %':<8}")
    print(f"    {'-'*20} {'-'*12} {'-'*8}")
    for name, err in [("Classical P1", l2_cl), ("Exact RFB", l2_ex), ("KAN-RFB", l2_kan)]:
        print(f"    {name:<20} {err:<12.4e} {relative_error_percentage(err, norm):<8.1f}")

# ── 8. GENERALIZATION SUMMARY ────────────────────────────────────────────
print("\n" + "=" * 70)
print("GENERALIZATION SUMMARY (bubble-level: KAN vs exact)")
print("=" * 70)
print("Rows 1–2: train-band samples (interpolation). Rows 3–4: OOD")
print("boundary-layer samples (Pe never seen during training).")
print("If the KAN-RFB errors stay close to the Exact RFB errors in the")
print("extrapolation rows, the KAN has learned a genuinely generalizable")
print("Pe↦shape map.\n")

for rp in rep_samples:
    pe_val = rp["pe"]
    rho_val = rp["rho"]
    eps_val = BETA * H / (2 * pe_val)
    sigma_val = rho_val * eps_val / H**2

    kan_pred = multi_model.value_grad_numpy(xi_plot, pe_val, rho_val)

    exact = ExactRFBubbleSet1D(eps_val, BETA, sigma_val, H,
                               residual_modes=("constant", "xi"), n_points=4000)
    exact_pred = exact.value_grad_numpy(xi_plot, pe_val, rho_val)

    for mode_i, mode_name in enumerate(["b̂ (constant)", "b̃ (xi)"]):
        mse_kan = np.mean((kan_pred[mode_i] - exact_pred[mode_i])**2)
        print(f"  {rp['name']:18s} | {mode_name:12s} | MSE(KAN vs Exact) = {mse_kan:.4e}")

# ── 9. PLOT SOLUTIONS AT THE REPRESENTATIVE SAMPLES ──────────────────────
fig, axes = plt.subplots(2, 2, figsize=(12, 8), sharex=True, sharey=True)
x_p = np.linspace(0, 1, 300)
N_EL = 16

for ax, rp in zip(axes.flat, rep_samples):
    pe_val = rp["pe"]
    rho_val = rp["rho"]
    EPS = BETA * H / (2 * pe_val)
    SIGMA = rho_val * EPS / H**2

    mesh = Mesh1D(0.0, 1.0, N_EL)
    quad = GaussLegendre(16)
    pde = AdvectionDiffusion1D(EPS, BETA, SIGMA)
    pde.set_source_from_function(lambda x: np.ones_like(x))

    # Fine FD reference
    N_FD = 8000
    dx_ref = 1.0 / (N_FD - 1)
    x_ref = np.linspace(0, 1, N_FD)
    A_ref = np.zeros((N_FD, N_FD))
    rhs_ref = np.ones(N_FD)
    for j in range(1, N_FD - 1):
        A_ref[j, j-1] = -EPS/dx_ref**2 - BETA/(2*dx_ref)
        A_ref[j, j]   =  2*EPS/dx_ref**2 + SIGMA
        A_ref[j, j+1] = -EPS/dx_ref**2 + BETA/(2*dx_ref)
    A_ref[0,0] = A_ref[-1,-1] = 1.0
    rhs_ref[0] = rhs_ref[-1] = 0.0
    u_ref = np.linalg.solve(A_ref, rhs_ref)

    # Classical P1
    A_cl, F_cl = assemble_classical_system(mesh, quad, pde)
    u_cl = np.linalg.solve(A_cl, F_cl)

    class ClassicalSol:
        def __init__(self, m, u): self.mesh = m; self.u = u
        def __call__(self, x):
            b = LagrangeBasis1D(self.mesh)
            return sum(self.u[i] * b.eval(x, i) for i in range(self.mesh.n_nodes))

    # Exact RFB
    exact_set = ExactRFBubbleSet1D(EPS, BETA, SIGMA, mesh.h,
                                   residual_modes=("constant", "xi"), n_points=8000)
    A_ex, F_ex, local_ex = assemble_rfb_condensed_system(mesh, quad, pde, exact_set)
    u_ex = np.linalg.solve(A_ex, F_ex)
    ub_ex = recover_bubble_coefficients(u_ex, mesh, local_ex)
    sol_ex = RFBSolution1D(u_ex, ub_ex, mesh, exact_set, pde)

    # KAN-RFB
    A_kan, F_kan, local_kan = assemble_rfb_condensed_system(mesh, quad, pde, multi_model)
    u_kan = np.linalg.solve(A_kan, F_kan)
    ub_kan = recover_bubble_coefficients(u_kan, mesh, local_kan)
    sol_kan = RFBSolution1D(u_kan, ub_kan, mesh, multi_model, pde)

    ax.plot(x_p, np.interp(x_p, x_ref, u_ref), 'k-', lw=1.5, label='Exact FD')
    ax.plot(x_p, ClassicalSol(mesh, u_cl)(x_p), '--', label='Classical P1')
    ax.plot(x_p, sol_ex(x_p), ':', lw=2, label='Exact RFB')
    ax.plot(x_p, sol_kan(x_p), '-.', lw=2, label='KAN-RFB')
    ax.set_title(f"{rp['name']}\nPe={pe_val:.1f}, ρ={rho_val:.1f}", fontsize=10)
    ax.grid(True, alpha=0.3)

axes[0, 0].legend(fontsize=8)
fig.supxlabel('x')
fig.supylabel('u(x)')
fig.suptitle("PDE solutions: train-band interpolation vs OOD boundary-layer "
             "extrapolation", fontsize=12, y=1.01)
fig.tight_layout()
plt.show()
